[package]
name = "wg-reresolve-dns"
description = "Re-resolve DNS of endpoints for Wireguard interfaces"
version = "2.0.0"
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive", "env"] }
rust-ini = "0.18"
wireguard-uapi = "2.0"
humantime = "2.1"
log = "0.4"
base64 = "0.13.0"
simple_logger = {version = "2.2", default-features = false }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = 'abort'
strip = true
